<?php

class DBComments {
	const COMMENT_TYPE_UNIFICATION;
	const COMMENT_TYPE_ATTRIBUTES_RADICAL;
	const COMMENT_TYPE_ATTRIBUTES_SC;
	const COMMENT_TYPE_ATTRIBUTES_TC;
	const COMMENT_TYPE_ATTRIBUTES_IDS;
	const COMMENT_TYPE_ATTRIBUTES_TRAD_SIMP;
	const COMMENT_TYPE_MISDESIGNED_GLYPH;
	const COMMENT_TYPE_ATTRIBUTES_REJECTION;
	const COMMENT_TYPE_UNCLEAR_EVIDENCE;
	const COMMENT_TYPE_EDITORIAL_ERROR;
	const COMMENT_TYPE_OTHER;
	
	public $db;
	public function __construct() {
		$this->db = Env::$db;
	}
}